name: Replace Sigma Placeholders

on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  replace_and_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v3
        with:
          ref: dev
          fetch-depth: 0

      - name: Set up Git identity
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

      - name: Create or checkout playbook-stable branch and fast-forward merge dev
        run: |
          git fetch origin
      
          # Check if playbook-stable branch exists
          if git show-ref --verify --quiet refs/heads/playbook-stable; then
            git checkout playbook-stable
            git pull origin playbook-stable
          else
            git checkout -b playbook-stable
          fi
      
          # Fast-forward only merge
          git merge --ff-only origin/dev
      
          # Check if fast-forward was successful
          if [ $? -ne 0 ]; then
            echo "Fast-forward merge failed. Manual intervention needed."
            exit 1
          fi


      - name: Replace patterns using patterns.sed
        run: |
          for file in $(find playbook/dev -type f -name '*.yaml'); do
            sed -i -f patterns.sed "$file"
          done
          
      - name: Commit and push if changes found
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git add .
            git commit -m "Replace Sigma placeholders using ECS mappings"
            git pull --rebase origin playbook-stable
            git push origin playbook-stable
          else
            echo "No changes to commit."
            exit 0
          fi
